// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1UfcfYUEARYQxQXOxYKBu_I41j0NvtYI',
    appId: '1:890911900034:web:89d4d7cd22d1d8c3bf8f9b',
    messagingSenderId: '890911900034',
    projectId: 'firstflutterapp-35a6c',
    authDomain: 'firstflutterapp-35a6c.firebaseapp.com',
    storageBucket: 'firstflutterapp-35a6c.appspot.com',
    measurementId: 'G-CZQZ1D07Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACYYp4fEmIdUBqy4iCCLqeMpGTyytHwRs',
    appId: '1:890911900034:android:d215796e91be54b9bf8f9b',
    messagingSenderId: '890911900034',
    projectId: 'firstflutterapp-35a6c',
    storageBucket: 'firstflutterapp-35a6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuC9L7UsrbNGKt6f6hBEfb2X4vCOTMlYU',
    appId: '1:890911900034:ios:1065c9dd15d2a2e4bf8f9b',
    messagingSenderId: '890911900034',
    projectId: 'firstflutterapp-35a6c',
    storageBucket: 'firstflutterapp-35a6c.appspot.com',
    iosClientId: '890911900034-r2gqeb27labq405eskh557lntqbnib6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuC9L7UsrbNGKt6f6hBEfb2X4vCOTMlYU',
    appId: '1:890911900034:ios:1065c9dd15d2a2e4bf8f9b',
    messagingSenderId: '890911900034',
    projectId: 'firstflutterapp-35a6c',
    storageBucket: 'firstflutterapp-35a6c.appspot.com',
    iosClientId: '890911900034-r2gqeb27labq405eskh557lntqbnib6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstflutterapp',
  );
}
